name: Rust CI

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install target
      run: rustup target add aarch64-unknown-none-softfloat
    - name: Build
      run: cargo build --verbose
  build-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install target
      run: rustup target add aarch64-unknown-none-softfloat
    - name: Build
      run: cargo build --release --verbose
