name: Rust

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install target
      run: rustup target add aarch64-unknown-none-softfloat
    - name: Build (debug)
      run: cargo build --verbose
    - name: Build (release)
      run: cargo build --release --verbose
